2022-04-05 16:09:04.291719: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-05 16:09:04.291818: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (69dc0e526fe3): /proc/driver/nvidia/version does not exist
2022-04-05 16:09:04.292313: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Using found mnist data
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
original [5514, 6314, 5599, 5707, 5431, 5058, 5516, 5840, 5484, 5531]
original 55994
original [1389, 1563, 1391, 1434, 1393, 1255, 1360, 1453, 1341, 1427]
original 14006
MAIN: Started Training
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
   label  score         0
i
0      2    NaN   1.00855
1      0    NaN  0.002884
2      4    NaN  0.008388
3      8    NaN  0.092359
6      0    NaN  2.347147
used 0 epoch
   label     score         0
i
0      2   1.00855   1.00855
1      0  0.002884  0.002884
2      4  0.008388  0.008388
3      8  0.092359  0.092359
6      0  2.347147  2.347147
       label  score         0
i
46967      2    0.0  0.000001
16404      2    1.0  0.000004
21600      3    2.0  0.000005
14616      3    3.0  0.000006
7341       0    4.0  0.000008
                                                     img  label  score
i
46967  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    0.0
16404  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    1.0
21600  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    2.0
14616  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    3.0
7341   [  0   0   0   0   0   0   0   0   0   0   0  ...      0    4.0
...                                                  ...    ...    ...
46668  [  0   0   0   0   0   0   0   0   0   0   0  ...      1    NaN
54380  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    NaN
60135  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    NaN
47956  [  0   0   0   0   0   0   0   0   0   0   0  ...      8    NaN
1500   [  0   0   0   0   0   0   0   0   0   0   0  ...      0    NaN
[55994 rows x 3 columns]
5599
[51827, 49729, 51595, 51078, 50985, 51070, 51145, 51022, 50623, 50471]
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2022-04-05 16:11:48.306473: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Epoch  1 , Loss:  0.48086718 , Accuracy:  0.86665595 , Test Loss:  0.2630758 , Test Accuracy:  0.9241276
Checkpoint saved
Batch =0
Batch =100
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
       label  score         0         1
i
46967      2    0.0  0.000001  0.000044
16404      2    1.0  0.000004  0.000109
21600      3    2.0  0.000005  0.000031
14616      3    3.0  0.000006  0.000007
7341       0    4.0  0.000008  0.000008
use reduced grads
Traceback (most recent call last):
  File "RunTest.py", line 193, in <module>
    main(args)
  File "RunTest.py", line 142, in main
    df_train_losses = sf.scoring_func(df_train_losses,info) # =(i|score,0,1,2...)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 147, in scoring_func
    df['score'] = calc_grad(n,df.iloc[:,-n:])
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 115, in calc_grad
    model = linear_model.LinearRegression().fit(x,y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_base.py", line 662, in fit
    X, y = self._validate_data(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 979, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 989, in _check_y
    y = check_array(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 122, in _assert_all_finite
    raise ValueError("Input contains NaN")
ValueError: Input contains NaN