
INIT: Using found mnist data
2022-04-05 15:04:23.213777: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-05 15:04:23.213855: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (69dc0e526fe3): /proc/driver/nvidia/version does not exist
2022-04-05 15:04:23.214106: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
MAIN: Started Training
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
   label  score         0
i
0      2    NaN  0.012537
1      0    NaN  0.009663
2      4    NaN  0.033667
3      8    NaN  0.183491
6      0    NaN  0.002063
used 0 epoch
   label     score         0
i
0      2  0.012537  0.012537
1      0  0.009663  0.009663
2      4  0.033667  0.033667
3      8  0.183491  0.183491
6      0  0.002063  0.002063
       label  score         0
i
29477      2    0.0  0.000007
8643       2    1.0  0.000007
25534      2    2.0  0.000008
33061      2    3.0   0.00001
8048       2    4.0   0.00001
                                                     img  label  score
i
29477  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    0.0
8643   [  0   0   0   0   0   0   0   0   0   0   0  ...      2    1.0
25534  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    2.0
33061  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    3.0
8048   [  0   0   0   0   0   0   0   0   0   0   0  ...      2    4.0
...                                                  ...    ...    ...
27786  [  0   0   0   0   0   0   0   0   0   0   0  ...      9    NaN
56932  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    NaN
66824  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    NaN
23191  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    NaN
47157  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    NaN
[55994 rows x 3 columns]
55994
[5514, 6314, 5599, 5707, 5431, 5058, 5516, 5840, 5484, 5531]
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2022-04-05 15:06:54.093972: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Epoch  1 , Loss:  0.5102077 , Accuracy:  0.8626 , Test Loss:  0.2635058 , Test Accuracy:  0.9200515
Checkpoint saved
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Traceback (most recent call last):
  File "RunTest.py", line 193, in <module>
    main(args)
  File "RunTest.py", line 134, in main
    col = sf.update_col(batch_loss,col,X[0],info) # = (i,current_epoch)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 195, in update_col
    new_row = pd.DataFrame(data={'i':indexes[i],str(info.current_epoch):batch_loss[i].numpy()},index=[0])
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/construction.py", line 482, in dict_to_mgr
    columns = Index(keys)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 534, in __new__
    subarr = _maybe_cast_data_without_dtype(  # type: ignore[assignment]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 7124, in _maybe_cast_data_without_dtype
    result = lib.maybe_convert_objects(
  File "pandas/_libs/lib.pyx", line 2461, in pandas._libs.lib.maybe_convert_objects
  File "/usr/local/lib/python3.8/dist-packages/numpy/core/numeric.py", line 289, in full
    @set_array_function_like_doc
KeyboardInterrupt