
INIT: Using found mnist data
2022-04-06 11:48:48.168984: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-06 11:48:48.169166: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (e175316c4453): /proc/driver/nvidia/version does not exist
2022-04-06 11:48:48.170477: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
MAIN: Started Training
Length Calculated:  1750
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
Traceback (most recent call last):
  File "RunTest.py", line 215, in <module>
    main(args)
  File "RunTest.py", line 142, in main
    class_loss_avg = [df_train_losses[df_train_losses.label==x].str(ce).mean() for x in range(train_data_gen.num_classes)]
  File "RunTest.py", line 142, in <listcomp>
    class_loss_avg = [df_train_losses[df_train_losses.label==x].str(ce).mean() for x in range(train_data_gen.num_classes)]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5583, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'str'