
INIT: Using found mnist data
2022-04-05 13:54:40.322351: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-05 13:54:40.322421: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (69dc0e526fe3): /proc/driver/nvidia/version does not exist
2022-04-05 13:54:40.322653: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
MAIN: Started Training
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
   label  score         0
i
0      2    NaN  0.046104
1      0    NaN   0.00931
2      4    NaN  0.002339
3      8    NaN  0.350882
6      0    NaN  0.001157
   label  score         0
i
0      2  29662  0.046104
1      0  29423   0.00931
2      4  52089  0.002339
3      8  47613  0.350882
6      0  26752  0.001157
       label  score         0
i
10014      5    0.0  0.322466
18426      8    1.0  0.313576
38546      4    2.0  0.056746
13275      3    3.0  0.070488
54111      5    4.0  0.010784
ON_EPOCH_END:
[5514, 6314, 5599, 5707, 5431, 5058, 5516, 5840, 5484, 5531]
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
Epoch  1 , Loss:  0.46470577 , Accuracy:  0.8753216 , Test Loss:  0.25571433 , Test Accuracy:  0.9259868
Checkpoint saved
Batch =0
2022-04-05 13:57:17.043988: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Batch =100
       label  score         0         1
i
10014      5    0.0  0.322466  0.415225
18426      8    1.0  0.313576  0.394539
38546      4    2.0  0.056746  0.006504
13275      3    3.0  0.070488  0.081022
54111      5    4.0  0.010784  0.004365
       label     score         0         1
i
10014      5  0.322466  0.322466  0.415225
18426      8  0.313576  0.313576  0.394539
38546      4  0.056746  0.056746  0.006504
13275      3  0.070488  0.070488  0.081022
54111      5  0.010784  0.010784  0.004365
       label  score         0    1
i
37369      0    0.0  0.000003  NaN
41028      0    1.0  0.000004  NaN
2172       0    2.0  0.000007  NaN
54341      2    3.0  0.000007  NaN
4493       0    4.0  0.000008  NaN
ON_EPOCH_END:
[5514, 6314, 5599, 5707, 5431, 5058, 5516, 5840, 5484, 5531]
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
Epoch  2 , Loss:  0.23019567 , Accuracy:  0.9313937 , Test Loss:  0.2416994 , Test Accuracy:  0.92963386
Batch =0
Batch =100
Batch =200
       label  score         0    1         2
i
37369      0    0.0  0.000003  NaN  0.000007
41028      0    1.0  0.000004  NaN  0.000045
2172       0    2.0  0.000007  NaN  0.000018
54341      2    3.0  0.000007  NaN   0.00007
4493       0    4.0  0.000008  NaN  0.000036
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
Traceback (most recent call last):
  File "RunTest.py", line 193, in <module>
    main(args)
  File "RunTest.py", line 142, in main
    df_train_losses = sf.scoring_func(df_train_losses,info) # =(i|score,0,1,2...)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 150, in scoring_func
    df['score'] = calc_grad(n,df.iloc[:,np.r_[0,-n:]])
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 115, in calc_grad
    model = linear_model.LinearRegression().fit(x,y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_base.py", line 662, in fit
    X, y = self._validate_data(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 981, in check_X_y
    check_consistent_length(X, y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 332, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [2, 1]