
INIT: Cannot find  mnist  data, downloading now...
2022-04-08 13:36:37.350696: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
[1mDownloading and preparing dataset 11.06 MiB (download: 11.06 MiB, generated: 21.00 MiB, total: 32.06 MiB) to /home/vscode/tensorflow_datasets/mnist/3.0.1...
Dl Completed...: 100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 4/4 [00:04<00:00,  1.19s/ file]
2022-04-08 13:36:44.755664: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-08 13:36:44.755896: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (c8f727e0b809): /proc/driver/nvidia/version does not exist
2022-04-08 13:36:44.762955: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1mDataset mnist downloaded and prepared to /home/vscode/tensorflow_datasets/mnist/3.0.1. Subsequent calls will reuse this data.
INIT: Finished creating train dataset
  label  score
i
0     4    NaN
1     1    NaN
2     0    NaN
3     7    NaN
4     8    NaN
class names:  ['0']
MAIN: Started Training
Number of batches to use:  1752
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
Traceback (most recent call last):
  File "RunTest.py", line 226, in <module>
    main(args)
  File "RunTest.py", line 141, in main
    for i, (X,Y) in enumerate(train_data_gen):
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py", line 486, in __iter__
    for item in (self[i] for i in range(len(self))):
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py", line 486, in <genexpr>
    for item in (self[i] for i in range(len(self))):
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 78, in __getitem__
    X, Y = self.__get_data(batches)
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 71, in __get_data
    X_batch = np.asarray([self.__get_input(x, self.input_size) for x  in img_batch])
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 71, in <listcomp>
    X_batch = np.asarray([self.__get_input(x, self.input_size) for x  in img_batch])
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 48, in __get_input
    img = img.replace('[','')
AttributeError: 'numpy.ndarray' object has no attribute 'replace'