
INIT: Using found mnist data
2022-04-05 16:20:10.571474: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-05 16:20:10.571572: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (69dc0e526fe3): /proc/driver/nvidia/version does not exist
2022-04-05 16:20:10.571807: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
original [5514, 6314, 5599, 5707, 5431, 5058, 5516, 5840, 5484, 5531]
original 55994
original [1389, 1563, 1391, 1434, 1393, 1255, 1360, 1453, 1341, 1427]
original 14006
MAIN: Started Training
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
   label  score         0
i
0      2    NaN  0.012702
1      0    NaN  0.391153
2      4    NaN  0.002651
3      8    NaN  0.764286
6      0    NaN  0.026372
used 0 epoch
   label     score         0
i
0      2  0.012702  0.012702
1      0  0.391153  0.391153
2      4  0.002651  0.002651
3      8  0.764286  0.764286
6      0  0.026372  0.026372
       label  score         0
i
45461      7    0.0  0.000009
14744      2    1.0  0.000013
31656      3    2.0  0.000014
52691      0    3.0  0.000014
10752      2    4.0  0.000015
                                                     img  label  score
i
45461  [  0   0   0   0   0   0   0   0   0   0   0  ...      7    0.0
14744  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    1.0
31656  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    2.0
52691  [  0   0   0   0   0   0   0   0   0   0   0  ...      0    3.0
10752  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    4.0
...                                                  ...    ...    ...
26786  [  0   0   0   0   0   0   0   0   0   0   0  ...      7    NaN
61816  [  0   0   0   0   0   0   0   0   0   0   0  ...      8    NaN
3572   [  0   0   0   0   0   0   0   0   0   0   0  ...      5    NaN
64921  [  0   0   0   0   0   0   0   0   0   0   0  ...      6    NaN
13583  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    NaN
[55994 rows x 3 columns]
5599
[1017, 279, 1187, 667, 427, 161, 777, 951, 129, 4]
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2022-04-05 16:22:48.873635: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Epoch  1 , Loss:  0.50870305 , Accuracy:  0.86133146 , Test Loss:  0.26014054 , Test Accuracy:  0.9223398
Checkpoint saved
Batch =0
Batch =100
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
       label  score         0         1
i
45461      7    0.0  0.000009  0.000007
14744      2    1.0  0.000013  0.000072
31656      3    2.0  0.000014  0.000008
52691      0    3.0  0.000014   0.00002
10752      2    4.0  0.000015  0.000041
use reduced grads
Traceback (most recent call last):
  File "RunTest.py", line 193, in <module>
    main(args)
  File "RunTest.py", line 142, in main
    df_train_losses = sf.scoring_func(df_train_losses,info) # =(i|score,0,1,2...)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 147, in scoring_func
    df['score'] = calc_grad(n,df.iloc[:,-n:])
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 115, in calc_grad
    model = linear_model.LinearRegression().fit(x,y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_base.py", line 662, in fit
    X, y = self._validate_data(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 979, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 989, in _check_y
    y = check_array(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').