INIT: Using found mnist data
INIT: Finished creating train dataset
   label  i   test
0      2  0  False
1      0  1  False
2      4  2  False
3      8  3  False
4      7  4   True
   label  i   test
0      2  0  False
1      0  1  False
2      4  2  False
3      8  3  False
4      7  4   True
MAIN: Started Training
2022-04-05 10:31:40.840674: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-05 10:31:40.840740: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (69dc0e526fe3): /proc/driver/nvidia/version does not exist
2022-04-05 10:31:40.841037: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "RunTest.py", line 182, in <module>
    main(args)
  File "RunTest.py", line 128, in main
    for i, (X,Y) in enumerate(train_data_gen):
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py", line 485, in __iter__
    for item in (self[i] for i in range(len(self))):
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py", line 485, in <genexpr>
    for item in (self[i] for i in range(len(self))):
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 72, in __getitem__
    self.b += 1
AttributeError: 'CustomDataGen' object has no attribute 'b'